name: Backend Lint & Analysis

on:
  pull_request:
    paths:
      - 'backend/**'

jobs:
  analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

      - name: Run PMD
        run: ./gradlew pmdMain

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain