name: Build & Publish Docker Images

on:
  # Only run when you publish a GitHub Release
  release:
    types: [published]
  # Also allow manual runs via the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU (for multi‑arch)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend          # point at the backend folder
          file: Dockerfile           # the Dockerfile inside backend/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/feedfusionai-backend:latest

      - name: Build & Push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend        # point at the frontend folder
          file: Dockerfile           # the Dockerfile inside frontend/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/feedfusionai-frontend:latest