name: Build & Publish Docker Images

on:
  # Trigger when you publish a GitHub Release
  release:
    types: [published]
  # Also allow manual runs from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build & Push images to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU (for multi‑arch builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags:
            - ${{ secrets.DOCKERHUB_USERNAME }}/feedfusionai-backend:latest

      - name: Build & push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags:
            - ${{ secrets.DOCKERHUB_USERNAME }}/feedfusionai-frontend:latest