name: Build & Publish Docker Images

on:
  # Trigger when you publish a GitHub Release
  release:
    types: [published]
  # Also allow manual runs via the Actions UI
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Debug working directory
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -R .

      - name: Set up QEMU (for multi‑arch)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/feedfusionai-backend:latest

      - name: Build & Push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/feedfusionai-frontend:latest